<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="10" hostname="asd" name="com.testng.AutoReRunKnow" tests="12" failures="1" timestamp="02 Feb 2020 07:28:36 GMT" time="48.440" errors="0">
  <testcase name="tc1" time="13.116" classname="com.testng.AutoReRunKnow"/>
  <testcase name="tc2" time="2.488" classname="com.testng.AutoReRunKnow">
    <failure type="java.lang.AssertionError" message="expected [louis] but found [xavier]">
      <![CDATA[java.lang.AssertionError: expected [louis] but found [xavier]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testng.AutoReRunKnow.tc2(AutoReRunKnow.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="3.353" classname="com.testng.AutoReRunKnow">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="2.701" classname="com.testng.AutoReRunKnow">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="2.573" classname="com.testng.AutoReRunKnow">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="2.751" classname="com.testng.AutoReRunKnow">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="2.410" classname="com.testng.AutoReRunKnow">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="2.572" classname="com.testng.AutoReRunKnow">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="3.156" classname="com.testng.AutoReRunKnow">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="5.517" classname="com.testng.AutoReRunKnow">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="5.571" classname="com.testng.AutoReRunKnow">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="2.232" classname="com.testng.AutoReRunKnow">
    <skipped/>
  </testcase> <!-- tc2 -->
</testsuite> <!-- com.testng.AutoReRunKnow -->
